<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Ansh Singh — Portfolio</title>
  <meta name="description" content="Personal portfolio of Ansh Singh — projects, skills, and work." />
